"""Reset and add is_reserved

Revision ID: 3779a5fc2aef
Revises: c4aacf0f7490
Create Date: 2025-02-03 12:21:52.095472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3779a5fc2aef'
down_revision = 'c4aacf0f7490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.drop_column('is_reserved')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reserved', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
