"""Reset and add is_reserved

Revision ID: 863c222fe8d5
Revises: 6fcf1dbd4937
Create Date: 2025-02-02 17:16:35.677897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863c222fe8d5'
down_revision = '6fcf1dbd4937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_reservation')
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reserved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.drop_column('is_reserved')

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    op.create_table('_alembic_tmp_reservation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fk_reservation_customer', sa.INTEGER(), nullable=False),
    sa.Column('fk_reservation_vehicle', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('start_time', sa.TIME(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('end_time', sa.TIME(), nullable=False),
    sa.Column('duration', sa.FLOAT(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['fk_reservation_customer'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['fk_reservation_vehicle'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
