"""Add vehicle status and maintenance fields

Revision ID: 865e6427360d
Revises: 
Create Date: 2024-10-22 12:55:25.229754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865e6427360d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maintenance_start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('maintenance_end', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.drop_column('maintenance_end')
        batch_op.drop_column('maintenance_start')

    # ### end Alembic commands ###
