"""empty message

Revision ID: b28b2d2ac7a3
Revises: 3779a5fc2aef
Create Date: 2025-02-03 12:27:41.516797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b28b2d2ac7a3'
down_revision = '3779a5fc2aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reserved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.drop_column('is_reserved')

    # ### end Alembic commands ###
